---
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE,
                      error=FALSE, warning=FALSE, comment=NA)
```

```{r packages}
# Ensures the package "pacman" is installed
if (!require("pacman")) install.packages("pacman")

pacman::p_load(dplyr,
               tidybayes,
               here)

# Download rstanarm's "Survival Analysis Version" 
# https://github.com/stan-dev/rstanarm

# install.packages("rstanarm", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))

library(rstanarm)
```


```{r load bayesian models}

# Posteriors
load(here::here("output/fit/bayesian_model_vague.RData"))
load(here::here("output/fit/bayesian_model_skeptical.RData"))
load(here::here("output/fit/bayesian_model_informative.RData"))
load(here::here("output/fit/bayesian_model_informative_100.RData"))

```

**Supplementary Material**


### Supplementary Table 1

<br><br>

```{r}
# Source: https://doi.org/10.1016/j.jclinepi.2019.10.015
# Section 4.2. Calculation of absolute effects for events (e.g., mortality)

RD_HR_fun = function(r0, HR){
  # r0 = baseline risk (no pacemaker group)
  # r1 = risk in the pacemaker group
  # HR = hazard ratio
  r1 = 1 - (1 - r0)^HR
  
  # RD = risk difference (%)
  100*(r1 - r0)
}

# Load digitalized data from KM curve on "No pacemaker" group

no_pace_data = read.csv(here::here("data/no_pacemaker_four_years_km.csv"),
                    header= TRUE)

# Extract risk at last time point 
baseline_risk = 
  
  # "100 -" is necessary because the original digitalized data regards "Cumulative Survival"
  # but we want the mortality risk
  # Thus, one needs to subtract 100 (%) by the survival value
  
  100 - no_pace_data[nrow(no_pace_data), 2]


rd_table_fun = function(model, col_name){
  rd = 
    model |> 
    tidybayes::tidy_draws() |> 
    dplyr::summarise(RD = RD_HR_fun(r0 = baseline_risk/100, HR = exp(treatPacemaker)))
  
  colnames(rd) = col_name
  
  return(rd)
}

RDs = rd_table_fun(vague, "Vague") |> 
  dplyr::bind_cols(
    rd_table_fun(skeptical_model, "Skeptical"),
    rd_table_fun(informative, "SAVR 50%"),
    rd_table_fun(informative_100, "SAVR 100%"),
  ) |> 
  tidyr::pivot_longer(1:4)

cri95 = 
  RDs |> 
  dplyr::group_by(name) |> 
  ggdist::median_hdi(value) |> 
  dplyr::mutate(dplyr::across(value:.upper, ~round(.,1))) |> 
  dplyr::summarise("Belief" = name,
                   "RD (95% CrI)" = stringr::str_c(
                     value, " (", .lower, ", ", .upper, ")"))

probs = 
  RDs |> 
  dplyr::group_by(name) |> 
  dplyr::summarise("RD >0%" = mean(value > 0),
                   "RD >1%" = mean(value > 1),
                   "RD >2%" = mean(value > 2)) |> 
  dplyr::mutate(dplyr::across(2:4, ~round(100*.,1))) |> 
  dplyr::rename("Belief" = name)

dplyr::left_join(cri95, probs) |> 
  dplyr::mutate(Belief = forcats::fct_rev(Belief)) |> 
  dplyr::arrange(Belief) |> 
  flextable::flextable() |> 
  flextable::autofit() |> 
  flextable::add_header_row(top = TRUE, 
                            values = c(" ", "Posterior probability, %"), 
                            colwidths = c(2, 3)) |> 
  flextable::theme_box() |> 
  flextable::add_footer_lines('The assumed fixed baseline risk was 39.9%, based on the SWEDEHEART TAVR data on patients not exposed to pacemaker at 4 years.') |> 
  flextable::add_footer_lines('"SAVR 50%" regards posterior distribution while assuming a prior based on the surgical aortic valve replacement SWEDEHEART data with 50% of weight. "SAVR 100%" regards the same data, but with 100% weight.') |> 
  flextable::add_footer_lines('Abbreviation: RD, risk difference')
```

